---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age12hwujmvcxdf0wazmgc7sxv2p603vqy5cl26qpsp6stqdfsa3cfcs4qwwth"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age12hwujmvcxdf0wazmgc7sxv2p603vqy5cl26qpsp6stqdfsa3cfcs4qwwth"
