apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:jrLP0bFg9iJ1cuu7OasdkJWDtJw6c/BBadqGuFoQGmeziyU1,iv:eGL1gUKyyTsqYWqiGKwe9/goNxwTv2m+CdlJuxhEAxY=,tag:COlqv9BK/K03VI62pHEYpA==,type:str]
    credentials.json: ENC[AES256_GCM,data:I5TlhKPR6YW1KBfp9UIeKx/uHqy9ETdeA8Nbrxt4Z8RqWq6z0WnDGOop1hjRYUExEMyMRQLo2YXGmV2Wr7WrsQc+BZoIAyStxkBM6jLrN8liR9zytG+KGUHqgMC/F+Es3K/aofy4F5M/O7D+kqnW9zOgT7xTeWJ94u6uMCF2StfHwLNlwm4TVkUoEhvA0aWFyAvPeDMLRMfEzYzOHPZaf21R5wd1+SBlsMSJrwA+hA==,iv:qpND9qHH3+ECi24AX9zBBU04hUNNVm0g8yg0HYwXKgU=,tag:Zw6eqVaTA5hV5LCT06h9bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12hwujmvcxdf0wazmgc7sxv2p603vqy5cl26qpsp6stqdfsa3cfcs4qwwth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTDdzci9YQXNsTHBVVERK
            ZStFMDZNRzEvcVhZNU1VQ2lRSDRCN3J0Zm4wCkIxaWg4bXUrTSt2YnVXb0RTTnV2
            T1JZbHlBYVkvbkhsOUpLanlKUDB4NTQKLS0tIGw5N2FkMUVjM21JeGxjSmZhKzNM
            TVVxNTFQZWxqSEVIRjE1dS9OVElERG8KbD16ka5GH1D8ObfczNtvnKkTfn3PJZfH
            vLEIAiuAdWyZQ0P7qONlmUHqaCNKYwRFqW9cHTglj/LduDbbk+/0bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T02:23:51Z"
    mac: ENC[AES256_GCM,data:rOXkDEaTi1Ns4jVNvfTTPMZ6CjOf877o9YyqQewZo9x74fOiqLycXNIZQkxopbElCs8Ks8COTetpRVQSbqUpvF26GSL6C2gfJ4mWKe4KtDogUlgu0hPK2z/LhpQszPx3G+DvGPnWrLZ9zgfZdPm+5fZ71H0pj0nO1eDdQ/tBQak=,iv:jn2zYH8FDhnmZ4jSvdz3e5Gz6mYP2nJot12TZ15cj6Q=,tag:IcxN4K9jNdSk7V4PNQyI2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
