apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:I+VF5ho8s4W43T/GMyWvPtQAGLick/XIeEMvBg2/gY/L6QRr5v1LZQ==,iv:6ZNyJcSXbMJXQ6QXhm5fvNMY0EL+OvxTFdfOiNpDPFI=,tag:ISbncxQyGFd0GtwDebgZPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12hwujmvcxdf0wazmgc7sxv2p603vqy5cl26qpsp6stqdfsa3cfcs4qwwth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcE5BVWIvR212SlBCTmx5
            MkhuaVVJc3VnU1VYYm9YMGdOKzZxTEhHZkZRCm9zWDl0T1hILytZbDZyNkZLS2hx
            Z0lTd1NwaWJOa0sxb3hROGFPZ2R5dmcKLS0tIEFtY2pPSCtaLzZ3QVRmOHc1a0pB
            a1lIWG1uNENQRjBUOGdUSjIvY0pIeFUKNzRgzu5LeWvF6wgzUyBjpTjzXa8VwFN6
            bO0+SBE1la0swgt0+FDi8t+dbTbz2CWUiLj+7lHdjLXNBz8voWG/rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T02:23:51Z"
    mac: ENC[AES256_GCM,data:c/fjrGLF8fnjxzZ+R8Y2MaGT10lfW+cUlGHem+i1Ataad5y80Zq8k34nXPjspRFYOK7ZpCyMYQuLiEaV9+LTyCbzaOh8edfPwlpjkK+9Z6Xwpy4gRWhsrUnAuJm2NzUswqHHcxqd3kOzu1vTepO1y5yYdqw0W6WVl8mG4GKyWk0=,iv:eff8qY/WLeq1uj/fd/w8D2T9DWI9rE+vmADraVRWvXA=,tag:VA2b6qmOBpuelAPeCLA1ZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
